### PR TITLE
fixed path of sw and resources & update document 

### PR DESCRIPTION
**Pull request by davidnguyen11**
I have pulled this project to my machine, when I finished start server and run. Service worker actually does nothing. So as my investigation, I saw that the path point to sw.js was wrong. I also update document to guild people to set up and run this example

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
I've tested this, and you are absolutely right! I'll merge this now. Also, sorry for taking so long to respond to this.

**Comment by bigZ-again** [comment]
@chrisdavidmills Please confirm it.

**Comment by chrisdavidmills** [comment]
OK, I know what's going on now. Your suggested changes broke the demo, because the paths were correct assuming the demo was being served from https://mdn.github.io/sw-test/.

If you want to serve the demo from somewhere else (e.g. localhost), you'll need to change the paths in the demo accordingly.

No harm done ;-)

**Comment by chrisdavidmills** [comment]
I fixed it, BTW.

**Comment by bigZ-again** [comment]
It's OK. Thanks.

**Pull request merged**
